# Generated by Django 6.0.5 on 2026-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_link',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
